# Generated by Django 3.0.6 on 2020-06-01 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_people', to='api.Profile')),
                ('to_person', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='to_people', to='api.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='relationships',
            field=models.ManyToManyField(related_name='related_to', through='api.Relationship', to='api.Profile'),
        ),
    ]
