# Generated by Django 3.0.6 on 2020-06-01 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200601_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='relationships',
            field=models.ManyToManyField(related_name='_profile_relationships_+', through='api.Relationship', to='api.Profile'),
        ),
    ]
