# Generated by Django 3.0.6 on 2020-06-01 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20200601_1656'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='relationship_person',
            new_name='social_user',
        ),
    ]
