# Generated by Django 3.0.7 on 2020-06-08 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_chat_participants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='person',
            name='social_user',
        ),
        migrations.AddField(
            model_name='socialuser',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_user', to='api.Person'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='api.Person'),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(),
        ),
    ]
