# Generated by Django 3.0.7 on 2020-06-08 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20200608_0640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialuser',
            name='person',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_user', to='api.Person'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='person',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='api.Person'),
        ),
    ]
